---
- name: Configure network interfaces
  hosts: ceph_servers
  become: yes
  tasks:
    - name: Ensure ens18 is DHCP
      community.general.interfaces_file:
        dest: "/etc/network/interfaces.d/ens18"
        iface: ens18
        option: "dhcp"
        state: present

    - name: Ensure ens19 is DHCP
      community.general.interfaces_file:
        dest: "/etc/network/interfaces.d/ens19"
        iface: ens19
        option: "dhcp"
        state: present

    - name: Apply network configuration
      shell: systemctl restart networking
      become: yes
