---
- name: Configure network interfaces
  hosts: servers
  become: yes
  tasks:
    - name: Configure ens18 as DHCP
      lineinfile:
        path: /etc/network/interfaces
        regexp: '^iface ens18'
        line: 'iface ens18 inet dhcp'
        state: present

    - name: Configure ens19 as DHCP
      lineinfile:
        path: /etc/network/interfaces
        regexp: '^iface ens19'
        line: 'iface ens19 inet dhcp'
        state: present
        
    - name: Restart networking service
      systemd:
        name: networking
        state: restarted
      become: yes
