---
- name: Configure NetworkManager
  hosts: servers
  become: true

  vars:
    ens18_settings:
      conn_name: ens18_connection
      conn_type: ethernet
      ifname: enp0s18  # Use the altname
      ip4: 192.200.0.1/16
      gw4: 192.200.0.1
      dns4:
        - 192.200.0.1

    ens19_settings:
      conn_name: ens19_connection
      conn_type: ethernet
      ifname: enp0s19  # Use the altname
      ip4: 172.200.0.1/16
      gw4: 172.200.0.1
      dns4:
        - 172.200.0.1

  tasks:
    - name: Install NetworkManager
      package:
        name: network-manager
        state: present

    - name: Add Ethernet connection settings for ens18
      nmcli:
        state: present
        conn_name: "{{ ens18_settings.conn_name }}"
        type: "{{ ens18_settings.conn_type }}"
        ifname: "{{ ens18_settings.ifname }}"
        ip4: "{{ ens18_settings.ip4 }}"
        gw4: "{{ ens18_settings.gw4 }}"
        dns4: "{{ ens18_settings.dns4 }}"

    - name: Add Ethernet connection settings for ens19
      nmcli:
        state: present
        conn_name: "{{ ens19_settings.conn_name }}"
        type: "{{ ens19_settings.conn_type }}"
        ifname: "{{ ens19_settings.ifname }}"
        ip4: "{{ ens19_settings.ip4 }}"
        gw4: "{{ ens19_settings.gw4 }}"
        dns4: "{{ ens19_settings.dns4 }}"

    - name: Restart NetworkManager
      systemd:
        name: NetworkManager
        state: restarted
