---
- name: Configure NetworkManager for DHCP
  hosts: servers
  become: yes
  
  tasks:
    - name: Install NetworkManager
      apt:
        name: network-manager
        state: present

    - name: Start NetworkManager service
      systemd:
        name: NetworkManager
        state: started
        enabled: yes

    - name: Ensure ens18 is using DHCP for IPv4 and IPv6
      nmcli:
        conn_name: connection_ens18
        type: ethernet
        ifname: ens18
        autoconnect: yes
        state: present
        ipv4.method: auto
        ipv6.method: auto

    - name: Ensure ens19 is using DHCP for IPv4 and IPv6
      nmcli:
        conn_name: connection_ens19
        type: ethernet
        ifname: ens19
        autoconnect: yes
        state: present
        ipv4.method: auto
        ipv6.method: auto

    - name: Restart NetworkManager
      systemd:
        name: NetworkManager
        state: restarted
