- name: Calculate next usable IP
  hosts: all  # Replace with the appropriate host group name
  gather_facts: yes
  tasks:
    - name: Calculate next usable IP
      set_fact:
        selected_ip: "{{ ansible_default_ipv4.network | ipaddr('next_usable') }}"
        
- name: Configure ens19 interface with static IP
  hosts: all  # Replace with the appropriate host group name
  become: true
  tasks:
    - name: Configure ens19 interface with static IP
      blockinfile:
        path: /etc/network/interfaces  # Modify the correct path based on your system's network configuration file
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          auto ens19
          iface ens19 inet static
              address {{ selected_ip }}/16
              netmask 255.255.0.0
              gateway 172.200.0.1
              dns-nameservers 172.200.0.1
