---
- name: Configure NetworkManager
  hosts: servers
  become: true

  vars:
    ens18_settings:
      conn_name: connection_ens18
      conn_type: ethernet
      ifname: ens18
      method: auto  # Use DHCP
      # No need to set ip4, gw4, or dns4 for DHCP

    ens19_settings:
      conn_name: connection_ens19
      conn_type: ethernet
      ifname: ens19
      method: auto  # Use DHCP
      # No need to set ip4, gw4, or dns4 for DHCP

  tasks:
    - name: Install NetworkManager
      package:
        name: network-manager
        state: present
        
    - name: Add Ethernet connection settings for ens18
      nmcli:
        state: present
        conn_name: "{{ ens18_settings.conn_name }}"
        type: "{{ ens18_settings.conn_type }}"
        ifname: "{{ ens18_settings.ifname }}"
        method: "{{ ens18_settings.method }}"
      async: 180
      poll: 0

    - name: Add Ethernet connection settings for ens19
      nmcli:
        state: present
        conn_name: "{{ ens19_settings.conn_name }}"
        type: "{{ ens19_settings.conn_type }}"
        ifname: "{{ ens19_settings.ifname }}"
        method: "{{ ens19_settings.method }}"
      async: 180
      poll: 0

    - name: Restart NetworkManager
      systemd:
        name: NetworkManager
        state: restarted
      async: 180
      poll: 0
