- name: Configure Hostname and /etc/hosts
  hosts: servers
  become: true
  tasks:
    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"
      register: hostname_result

    - name: Update /etc/hostname
      lineinfile:
        path: /etc/hostname
        line: "{{ inventory_hostname }}"
      when: hostname_result.changed

- name: Check current hostname and update /etc/hosts if needed
  hosts: servers
  become: true
  tasks:
    - name: Read current hostname from /etc/hostname
      slurp:
        src: /etc/hostname
      register: current_hostname

    - name: Compare current hostname with inventory hostname
      set_fact:
        hostname_match: "{{ current_hostname.content | b64decode | regex_search(inventory_hostname) | bool }}"

    - name: Update /etc/hosts for current hostname
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1\s+.*$'
        line: "127.0.1.1 {{ inventory_hostname }}.homelabbity.uk {{ inventory_hostname }}"
