- name: Configure ens18 and ens19 interfaces
  hosts: all  # Replace with the appropriate host group name
  become: true
  vars:
    network_connection_static:
      - name: static-network
        type: ethernet
        state: up
        ip:
          dhcp: no
          address: "{{ selected_ip }}/16"
          gateway4: 172.200.0.1
          dns:
            - 172.200.0.1

  tasks:
    - name: Get available IPs
      set_fact:
        available_ips: "{{ (100 + ansible_play_batch.index + 1) | format('172.200.0.%d') }}"
      run_once: true

    - name: Configure ens19 interface with static IP
      nmcli:
        conn_name: "{{ item.name }}"
        type: "{{ item.type }}"
        state: "{{ item.state }}"
        ifname: ens19
        ip4: "{{ item.ip }}"
      loop: "{{ network_connection_static }}"
      loop_control:
        loop_var: item
      vars:
        selected_ip: "{{ available_ips }}"

    - name: Configure ens18 interface with DHCP
      nmcli:
        conn_name: dhcp-network
        type: ethernet
        state: up
        ifname: ens18
        ip4: "dhcp"  # This indicates DHCP configuration
      loop_control:
        loop_var: item
