- name: Configure ens18 and ens19 interfaces
  hosts: all  # Replace with the appropriate host group name
  become: true
  vars:
    network_connection_static:
      - name: static-network
        type: ethernet
        state: up
        ip:
          dhcp: no
          address: "{{ selected_ip }}/16"
          gateway4: 172.200.0.1
          dns:
            - 172.200.0.1

  tasks:
    - name: Calculate next usable IP
      set_fact:
        selected_ip: "{{ '172.200.0.1/16' | ansible.utils.ipaddr('next_usable') }}"
      when: not selected_ip

    - name: Configure ens19 interface with static IP
      nmcli:
        conn_name: "{{ network_connection_static[0].name }}"
        type: "{{ network_connection_static[0].type }}"
        state: "{{ network_connection_static[0].state }}"
        ifname: ens19
        ip4: "{{ network_connection_static[0].ip }}"
      vars:
        network_connection_static: "{{ network_connection_static | first }}"

    - name: Configure ens18 interface with DHCP
      nmcli:
        conn_name: dhcp-network
        type: ethernet
        state: up
        ifname: ens18
        ip4: "dhcp"  # This indicates DHCP configuration
