- name: Configure ens18 and ens19 interfaces
  hosts: all  # Replace with the appropriate host group name
  become: true
  vars:
    available_ip_range_start: 100
    available_ip_range_end: 130

    network_connection_static:
      - name: static-network
        type: ethernet
        state: up
        ip:
          dhcp: no
          address: "{{ selected_ip }}/16"
          gateway4: 172.200.0.1
          dns:
            - 172.200.0.1

  tasks:
    - name: Get available IP
      set_fact:
        selected_ip: "172.200.0.{{ item }}"
      loop: "{{ range(available_ip_range_start, available_ip_range_end) }}"
      when: "not selected_ip"  # This ensures we stop once an IP is selected

    - name: Configure ens19 interface with static IP
      nmcli:
        conn_name: "{{ network_connection_static[0].name }}"
        type: "{{ network_connection_static[0].type }}"
        state: "{{ network_connection_static[0].state }}"
        ifname: ens19
        ip4: "{{ network_connection_static[0].ip }}"
      vars:
        network_connection_static: "{{ network_connection_static | first }}"

    - name: Configure ens18 interface with DHCP
      nmcli:
        conn_name: dhcp-network
        type: ethernet
        state: up
        ifname: ens18
        ip4: "dhcp"  # This indicates DHCP configuration
