---
- name: Configure NetworkManager
- hosts: servers
  become: true
  
  tasks:
    - name: Install NetworkManager
      package:
        name: network-manager
        state: present

    - name: Start NetworkManager service
      systemd:
        name: NetworkManager
        state: started
        enabled: true

    - name: Add an Ethernet connection with DHCP IP configuration (ens18)
      nmcli:
        conn_name: connection_ens18
        ifname: ens18
        type: ethernet
        ip4: dhcp
        state: present

    - name: Add an Ethernet connection with DHCP IP configuration (ens19)
      nmcli:
        conn_name: connection_ens19
        ifname: ens19
        type: ethernet
        ip4: dhcp
        state: present

    - name: Restart NetworkManager
      systemd:
        name: NetworkManager
        state: restarted
