---
- name: Configure ens18 and ens19 interfaces
  hosts: all  # Replace with the appropriate host group name
  become: true

  vars:
    network_connection_static:
      - name: static-network
        type: ethernet
        state: up

  tasks:
    - name: Generate network configuration file
      template:
        src: "https://raw.githubusercontent.com/brynjolm/ansible/main/playbook/ceph-interfaces.j2"
        dest: "/etc/network/interfaces.d/{{ network_connection_static[0].name }}"
