---
- name: Configure NetworkManager and Transition from ifupdown
  hosts: servers
  become: true
  
  tasks:
    - name: Install NetworkManager
      apt:
        name: network-manager
        state: present

    - name: Start NetworkManager service
      systemd:
        name: NetworkManager
        state: started
        enabled: yes

    - name: Disable and stop ifupdown
      systemd:
        name: ifupdown
        state: stopped
        enabled: no

    - name: Ensure ens18 is using DHCP for IPv4
      command: nmcli con add type ethernet ifname ens18 autoconnect yes ipv4.method auto
      become: yes

    - name: Ensure ens19 is using DHCP for IPv4
      command: nmcli con add type ethernet ifname ens19 autoconnect yes ipv4.method auto
      become: yes

    - name: Restart NetworkManager
      systemd:
        name: NetworkManager
        state: restarted
