---
- name: Configure ens19 interface with static IP
  hosts: all
  become: true
  vars:
    network_connection_static:
      - name: ens19
        ip: "{{ next_usable_ip }}/16"
        gateway: 172.200.0.1
        dns: 172.200.0.1

  tasks:
    - name: Calculate next usable IP
      set_fact:
        next_usable_ip: "{{ '172.200.0.2' | ipaddr('next_usable') }}"

- name: Generate network configuration file
  template:
    src: "https://raw.githubusercontent.com/brynjolm/ansible/main/playbook/ceph-interfaces.j2"
    dest: "/etc/network/interfaces.d/{{ network_connection_static[0].name }}"
  notify: Apply network configuration

      # Run handlers to apply network configuration changes
      notify: Apply network configuration

  handlers:
    - name: Apply network configuration
      systemd:
        name: networking
        state: restarted
