---
- name: Configure NetworkManager and Transition from ifupdown
  hosts: your_server_group
  become: yes
  
  tasks:
    - name: Install NetworkManager
      apt:
        name: network-manager
        state: present

    - name: Start NetworkManager service
      systemd:
        name: NetworkManager
        state: started
        enabled: yes

    - name: Ensure ens18 is using DHCP for IPv4
      nmcli:
        cmd: connection
        name: connection_ens18
        type: ethernet
        ifname: ens18
        autoconnect: yes
        state: present
        ip4: dhcp

    - name: Ensure ens19 is using DHCP for IPv4
      nmcli:
        cmd: connection
        name: connection_ens19
        type: ethernet
        ifname: ens19
        autoconnect: yes
        state: present
        ip4: dhcp

    - name: Ensure ens18 is using DHCP for IPv6
      nmcli:
        cmd: connection
        name: connection_ens18
        type: ethernet
        ifname: ens18
        autoconnect: yes
        state: present
        ip6: dhcp

    - name: Ensure ens19 is using DHCP for IPv6
      nmcli:
        cmd: connection
        name: connection_ens19
        type: ethernet
        ifname: ens19
        autoconnect: yes
        state: present
        ip6: dhcp

    - name: Restart NetworkManager
      systemd:
        name: NetworkManager
        state: restarted
