- name: Configure Hostname and /etc/hosts
  hosts: servers
  become: true
  tasks:
    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"
      register: hostname_result

    - name: Update /etc/hostname
      lineinfile:
        path: /etc/hostname
        line: "{{ inventory_hostname }}"
      when: hostname_result.changed

    - name: Update /etc/hosts for current hostname
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.0\.1\s+(?!{{ inventory_hostname }}\s*\n).*'
        line: "127.0.0.1 {{ inventory_hostname }}"

    - name: Update /etc/hosts for previous hostname entry
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.0\.1\s+{{ inventory_hostname }}'
        state: absent
