---
- name: Regenerate Host Keys and Verify OpenSSH Configuration
  hosts: all
  become: true
  tasks:
    - name: Regenerate Host Keys and Update Configuration
      command: dpkg-reconfigure openssh-server

    - name: Copy Host Key Private Files to Control Node
      fetch:
        src: "/etc/ssh/ssh_host_{{ item }}_key"
        dest: "copy/{{ inventory_hostname }}/"
        flat: yes
      loop:
        - rsa
        - ecdsa
        - ed25519
      become: true

    - name: Copy Host Key Private Files to Control Node
      fetch:
        src: "/etc/ssh/ssh_host_{{ item }}_key"
        dest: "copy/{{ inventory_hostname }}/"
        flat: yes
      loop:
        - rsa
        - ecdsa
        - ed25519
      become: true

    - name: Restart OpenSSH service
      service:
        name: sshd
        state: restarted

    - name: Wait for OpenSSH to restart
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 10
        timeout: 120
      register: ssh_restart_result
      until: ssh_restart_result is success

    - name: Check SSH Connectivity
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 5
        timeout: 30
      register: ssh_connect_result
      until: ssh_connect_result is success
