---
- name: Regenerate Host Keys and Verify OpenSSH Configuration
  hosts: all
  become: true
  tasks:
    - name: Regenerate Host Keys and Update Configuration
      command: dpkg-reconfigure openssh-server

    - name: Copy Host Key Public Files to Known Hosts
      lineinfile:
        path: ~/.ssh/known_hosts
        line: "{{ lookup('file', 'copy/' + inventory_hostname + '/ssh_host_' + item + '_key.pub') }}"
      loop:
        - rsa
        - dsa
        - ecdsa
        - ed25519
      become: true

    - name: Update known_hosts on Control Node
      local_action: command cat "copy/{{ inventory_hostname }}/ssh_host_*_key.pub >> ~/.ssh/known_hosts"
      become: true

    - name: Restart OpenSSH service
      service:
        name: sshd
        state: restarted

    - name: Wait for OpenSSH to restart
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 10
        timeout: 120
      register: ssh_restart_result
      until: ssh_restart_result is success

    - name: Check SSH Connectivity
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 5
        timeout: 30
      register: ssh_connect_result
      until: ssh_connect_result is success
