- name: Regenerate Host Keys and Verify OpenSSH Configuration
  hosts: servers
  become: true
  tasks:
    - name: Regenerate Host Keys and Update Configuration
      command: dpkg-reconfigure openssh-server

    - name: Copy Host Key Private Files to Control Node
      fetch:
        src: "/etc/ssh/ssh_host_{{ item }}_key"
        dest: "copy/{{ inventory_hostname }}/"
        flat: yes
      loop:
        - rsa
        - ecdsa
        - ed25519
      become: true

    - name: Restart OpenSSH service
      service:
        name: sshd
        state: restarted
