- name: Verify SSH Host Keys
  hosts: servers
  become: true
  tasks:
    - name: Fetch Remote Host Key
      command: ssh-keyscan -t rsa,ecdsa,ed25519 {{ inventory_hostname }}
      register: remote_keyscan_result

    - name: Read Local Known Hosts File
      slurp:
        src: "/root/.ssh/known_hosts"  # Replace with the actual path on your control node
      register: local_known_hosts_content
      delegate_to: localhost

    - name: Debug Remote Key
      debug:
        var: remote_keyscan_result.stdout_lines[0]

    - name: Debug Local Known Hosts Content
      debug:
        var: local_known_hosts_content.content

    - name: Compare Remote and Local Known Hosts Keys
      assert:
        that:
          - remote_keyscan_result.stdout_lines[0] == local_known_hosts_content.content
        fail_msg: "Host key does not match known hosts!"
      ignore_errors: yes
