---
- name: Verify OpenSSH Configuration
  hosts: all
  become: true
  tasks:
    - name: Read Host Key Public Files from Target VMs
      slurp:
        src: "/etc/ssh/ssh_host_{{ item }}_key.pub"
      register: host_key_content
      loop:
        - rsa
        - ecdsa
        - ed25519

- name: Compare Host Keys
  hosts: localhost
  tasks:
    - name: Compare Host Key Entries
      slurp:
        src: "{{ item }}"
      register: local_known_hosts
      loop: "{{ host_key_content.results | map(attribute='content') | list }}"

    - name: Debug Host Key Comparison
      debug:
        msg: "Host keys match."
      when: local_known_hosts.results | map(attribute='content') | list == host_key_content.results | map(attribute='content') | list
