---
- name: Verify OpenSSH Configuration
  hosts: all
  become: true
  tasks:
    - name: Read Host Key Public Files from Target VMs
      slurp:
        src: "/etc/ssh/ssh_host_{{ item }}_key.pub"
      register: host_key_content
      loop:
        - rsa
        - ecdsa
        - ed25519

- name: Compare Host Keys
  hosts: localhost
  tasks:
    - name: Read Local Known Hosts File
      slurp:
        src: "{{ lookup('env', 'HOME') + '/.ssh/known_hosts' }}"
      register: local_known_hosts_content

    - name: Compare Host Key Entries
      slurp:
        src: "path/to/fetched_host_keys_file"
      register: fetched_host_keys

    - name: Debug Host Key Comparison
      debug:
        msg: "Host keys match."
      when: local_known_hosts_content.content == fetched_host_keys.content
