---
- name: Perform Daily Apt Update
  hosts: all
  become: true  # Privilege escalation to run as root (sudo)
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes
      register: update_result

    - name: Display update result
      debug:
        var: update_result
